DO $test$
DECLARE f jsonb; store uuid; request uuid; quote uuid; session uuid; hash text; value jsonb; other jsonb;
BEGIN
 f:=photo_test.create_request(true,'store_prepaid'); store:=(f->>'store_id')::uuid;
 request:=(f->>'request_id')::uuid; quote:=(f->>'quote_id')::uuid;
 UPDATE public.direct_order_requests SET state='quoted' WHERE id=request;
 UPDATE public.direct_order_quotes SET status='active',created_at=now()-interval '2 hours',expires_at=now()-interval '1 hour' WHERE id=quote;
 UPDATE public.direct_order_quotes SET amount_finalized_at=now() WHERE id=quote;
 value:=public.direct_order_staff_quote_with_payment_mode(store,request,0,'Send again','store_prepaid');
 IF value->>'id'<>quote::text OR (SELECT count(*) FROM public.direct_order_quotes WHERE request_id=request)<>1 THEN
  RAISE EXCEPTION 'IDENTICAL_QUOTE_REPLACED'; END IF;
 BEGIN PERFORM public.direct_order_staff_quote_with_payment_mode(store,request,10000,NULL,'store_prepaid'); RAISE EXCEPTION 'FINAL_AMOUNT_CHANGED';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_FINAL_AMOUNT_LOCKED' THEN RAISE; END IF; END;
 BEGIN UPDATE public.direct_order_request_items SET quantity=quantity+1 WHERE request_id=request; RAISE EXCEPTION 'QUOTED_ITEMS_CHANGED';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_FINAL_AMOUNT_LOCKED' THEN RAISE; END IF; END;
 BEGIN UPDATE public.direct_order_quotes SET final_total=final_total+1 WHERE id=quote; RAISE EXCEPTION 'FINAL_AMOUNT_ROW_CHANGED';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_FINAL_AMOUNT_LOCKED' THEN RAISE; END IF; END;
 BEGIN DELETE FROM public.direct_order_quotes WHERE id=quote; RAISE EXCEPTION 'FINAL_AMOUNT_ROW_DELETED';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_FINAL_AMOUNT_LOCKED' THEN RAISE; END IF; END;
 SELECT session_id INTO session FROM public.direct_order_requests WHERE id=request;
 SELECT secret_hash INTO hash FROM public.direct_order_sessions WHERE id=session;
 value:=public.direct_order_public_status_v5(session,hash,request);
 IF (value->'quote') ? 'amount_finalized_at' THEN RAISE EXCEPTION 'LEGACY_STATUS_PAYLOAD_CHANGED'; END IF;
 value:=public.direct_order_public_status_v6(session,hash,request);
 IF value->'quote'->>'amount_finalized_at' IS NULL THEN RAISE EXCEPTION 'FINAL_AMOUNT_NOT_EXPOSED_IN_V6'; END IF;
 IF EXISTS(SELECT 1 FROM pg_proc WHERE oid IN ('public.direct_order_public_status_v5(uuid,text,uuid)'::regprocedure,'public.direct_order_public_status_v6(uuid,text,uuid)'::regprocedure) AND provolatile<>'v') THEN RAISE EXCEPTION 'STATUS_SESSION_ACTIVITY_NOT_VOLATILE'; END IF;
 value:=public.direct_order_public_commit_proof_v2(session,hash,request,quote,store::text||'/'||request::text||'/'||gen_random_uuid()::text||'.jpg',NULL);
 IF value->>'state'<>'awaiting_payment_review' THEN RAISE EXCEPTION 'FINALIZED_EXPIRED_PROOF_REJECTED'; END IF;
 PERFORM public.direct_order_issue_access(session,hash,request,repeat('a',64));
 PERFORM public.direct_order_issue_access(session,hash,request,repeat('a',64));
 IF (SELECT count(*) FROM public.direct_order_access_keys WHERE request_id=request)<>1 THEN RAISE EXCEPTION 'ACCESS_ISSUANCE_NOT_IDEMPOTENT'; END IF;
 UPDATE public.direct_order_sessions SET created_at=now()-interval '90 days',expires_at=now()-interval '1 day' WHERE id=session;
 value:=public.direct_order_resolve_access(request,repeat('a',64));
 IF value->>'session_id'<>session::text OR NOT EXISTS(SELECT 1 FROM public.direct_order_sessions WHERE id=session AND expires_at>now()) THEN RAISE EXCEPTION 'ORDER_LINK_LOST_WITH_SESSION_TTL'; END IF;
 BEGIN PERFORM public.direct_order_resolve_access(request,repeat('b',64)); RAISE EXCEPTION 'INVALID_ORDER_KEY_ACCEPTED';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_UNAVAILABLE' THEN RAISE; END IF; END;
 other:=photo_test.create_request(true,'store_prepaid');
 BEGIN PERFORM public.direct_order_issue_access(session,hash,(other->>'request_id')::uuid,repeat('c',64)); RAISE EXCEPTION 'OTHER_CUSTOMER_LINK_ISSUED';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_UNAVAILABLE' THEN RAISE; END IF; END;
 INSERT INTO public.direct_order_payment_receipts(request_id,restaurant_id,quote_id,proof_message_id,amount,bank_reference,confirmed_by) SELECT request,store,quote,(SELECT id FROM public.direct_order_messages WHERE request_id=request AND message_type='payment_proof' ORDER BY created_at DESC,id DESC LIMIT 1),1,'ADVANCE-FIXTURE',auth.uid();
 UPDATE public.direct_order_requests SET state='cancelled' WHERE id=request;
 PERFORM public.direct_order_resolve_access(request,repeat('a',64));
 UPDATE public.direct_order_requests SET support_closed_at=now() WHERE id=request;
 BEGIN PERFORM public.direct_order_resolve_access(request,repeat('a',64)); RAISE EXCEPTION 'CLOSED_ORDER_LINK_ACCEPTED';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_ORDER_CLOSED' THEN RAISE; END IF; END;
 IF NOT EXISTS(SELECT 1 FROM public.direct_order_access_keys WHERE request_id=request AND revoked_at IS NOT NULL) THEN RAISE EXCEPTION 'ORDER_KEY_NOT_REVOKED'; END IF;
 other:=photo_test.create_request(true,'store_prepaid');
 SELECT session_id INTO session FROM public.direct_order_requests WHERE id=(other->>'request_id')::uuid;
 SELECT secret_hash INTO hash FROM public.direct_order_sessions WHERE id=session;
 PERFORM public.direct_order_issue_access(session,hash,(other->>'request_id')::uuid,repeat('d',64));
 UPDATE public.direct_order_requests SET state='cancelled' WHERE id=(other->>'request_id')::uuid;
 BEGIN PERFORM public.direct_order_resolve_access((other->>'request_id')::uuid,repeat('d',64)); RAISE EXCEPTION 'UNFUNDED_CANCELLED_LINK_OPEN';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'DIRECT_ORDER_ORDER_CLOSED' THEN RAISE; END IF; END;
END;
$test$;
SELECT 'DIRECT_ORDER_FINAL_AMOUNT_AND_ACCESS=PASS';
