BEGIN;
DO $contract$
DECLARE buyer jsonb:=jsonb_build_object('system','office','subject_id',test_uuid(9901),'store_id',test_uuid(101),'can_manage',true,'can_create',true,'can_office_approve',true,'can_view_prices',true);
 senior jsonb; r jsonb;qid uuid;rid uuid;lid uuid;po jsonb;data jsonb;payload jsonb;doc jsonb;receipt uuid:=test_uuid(9908);path text;before_stock numeric;accepted jsonb;config_version integer;issue_id uuid;followup_id uuid;second_receipt uuid:=test_uuid(9909);payment_payload jsonb;prior_payment jsonb;pr_document_hash text;
BEGIN
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 SELECT row_version INTO config_version FROM public.procurement_store_policies WHERE restaurant_id=test_uuid(101);
 r:=public.procurement_command(test_uuid(101),'configure',NULL,COALESCE(config_version,0),'new-policy','{"enabled":true,"three_stage_required":true,"high_value_amount":1000000,"max_price_increase_percent":20,"quantity_review_multiplier":100}',buyer);
 r:=public.procurement_command(test_uuid(101),'configure',NULL,(r->>'row_version')::integer,'pause-policy','{"enabled":true,"new_requests_enabled":false,"high_value_amount":1000000,"max_price_increase_percent":20,"quantity_review_multiplier":100}',buyer);
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,NULL,0,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'create_request','paused-create','{"reason":"Paused","requested_delivery_date":"2026-10-06","lines":[]}',buyer),'PROCUREMENT_NEW_REQUESTS_PAUSED');
 r:=public.procurement_command(test_uuid(101),'configure',NULL,(r->>'row_version')::integer,'resume-policy','{"enabled":true,"new_requests_enabled":true,"high_value_amount":1000000,"max_price_increase_percent":20,"quantity_review_multiplier":100}',buyer);
 r:=public.procurement_command(test_uuid(101),'assign_principal',NULL,0,'link-person',jsonb_build_object('system','pos','subject_id',test_uuid(1),'person_id',test_uuid(901),'stage','requester','valid_from',now()-interval '1 day','valid_until',now()+interval '30 days','reason','Explicit workforce mapping','employee_confirmation',jsonb_build_object('employee_id',test_uuid(901),'pos_store_id',test_uuid(101),'name','Requester')),buyer);
 r:=public.procurement_command(test_uuid(101),'assign_principal',NULL,0,'link-other-auth',jsonb_build_object('system','office','subject_id',test_uuid(902),'person_id',test_uuid(901),'stage','brand','valid_from',now()-interval '1 day','valid_until',now()+interval '30 days','reason','Same person second Auth system','employee_confirmation',jsonb_build_object('employee_id',test_uuid(901),'pos_store_id',test_uuid(101),'name','Requester'),'principal_confirmation',jsonb_build_object('subject_id',test_uuid(902))),buyer);
 data:=public.procurement_workspace_page(test_uuid(101),'{"include_metrics":true}',buyer);ASSERT data->'operating_metrics'->>'window_days'='90';ASSERT jsonb_array_length(data->'operating_metrics'->'missing_stages')=5;
 -- Nonstock is a catalog classification, copied immutably to PO lines.
 UPDATE public.inventory_products SET specification='A4 pack',receipt_classification='nonstock',inventory_item_id=NULL WHERE id=test_uuid(301);
 PERFORM set_config('request.jwt.claim.role','authenticated',true);PERFORM set_config('request.jwt.claim.sub',test_uuid(1)::text,true);
 payload:=jsonb_build_object('reason','Office stationery','requested_delivery_date',current_date+2,'purchase_category','stationery','purchase_channel','shopee',
 'lines',jsonb_build_array(jsonb_build_object('product_id',test_uuid(301),'quantity',20,'unit','g','preferred_supplier_id',test_uuid(201))));
 r:=public.procurement_command(test_uuid(101),'create_request',NULL,0,'strict-create',payload);rid:=(r->>'id')::uuid;
 ASSERT (r->>'approval_policy_version')::integer=2;ASSERT r->>'purchase_channel'='shopee';
 SELECT id INTO lid FROM public.inventory_purchase_request_lines WHERE request_id=rid AND active;
 r:=public.procurement_command(test_uuid(101),'submit_request',rid,1,'strict-submit');ASSERT r->>'submitted_at' IS NOT NULL;
 pr_document_hash:=public.procurement_document_data(test_uuid(101),'pr',rid,'internal')->>'source_hash';
 data:=public.procurement_workspace_page(test_uuid(101),jsonb_build_object('request_id',rid));
 ASSERT data->'supplier_items'->0 ? 'unit_price';ASSERT data->'request_detail'->'lines'->0->>'estimated_unit_price' IS NOT NULL;
 ASSERT NOT(data->'request_detail' ? 'approved_amount');ASSERT NOT(data->'requests'->0 ? 'approval_snapshot');
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,2,%L,%L::jsonb)',test_uuid(101),'store_approve',rid,'self-store','{}'),'PROCUREMENT_SELF_APPROVAL_FORBIDDEN');
 PERFORM set_config('request.jwt.claim.sub',test_uuid(2)::text,true);
 payload:=jsonb_build_object('reason','Adjust to demand','lines',jsonb_build_array(jsonb_build_object('request_line_id',lid,'quantity',10)));
 r:=public.procurement_command(test_uuid(101),'adjust_request',rid,2,'strict-adjust',payload);
 ASSERT (SELECT quantity_base FROM public.inventory_purchase_request_lines WHERE id=lid)=10;
 r:=public.procurement_command(test_uuid(101),'store_approve',rid,3,'strict-store');ASSERT r->>'status'='brand_review';
 ASSERT public.procurement_document_data(test_uuid(101),'pr',rid,'internal')->>'source_hash'<>pr_document_hash,'PR export identity must include changed approvals';
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,4,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'office_approve',rid,'skip-brand','{}',buyer),'PROCUREMENT_OFFICE_FORBIDDEN');
 PERFORM set_config('request.jwt.claim.role','authenticated',true);PERFORM set_config('request.jwt.claim.sub',test_uuid(3)::text,true);
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,4,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'brand_approve',rid,'cross-auth-self','{}',buyer||jsonb_build_object('subject_id',test_uuid(902),'can_brand_approve',true)),'PROCUREMENT_SELF_APPROVAL_FORBIDDEN');
 PERFORM set_config('request.jwt.claim.role','authenticated',true);
 r:=public.procurement_command(test_uuid(101),'brand_approve',rid,4,'strict-brand');ASSERT r->>'status'='office_review';
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 payload:=jsonb_build_object('supplier_id',test_uuid(201),'valid_until',current_date+2,'delivery_date',current_date+2,'payment_terms','Net 7','evidence_reference','Written quote',
 'lines',jsonb_build_array(jsonb_build_object('request_line_id',lid,'supplier_item_id',test_uuid(401),'quantity_base',10,'unit_price',110,'tax_rate',0)));
 r:=public.procurement_command(test_uuid(101),'save_quote',rid,5,'strict-quote',payload,buyer);
 SELECT id INTO qid FROM public.procurement_quotes WHERE request_id=rid;
 r:=public.procurement_command(test_uuid(101),'select_quote',rid,6,'strict-select',jsonb_build_object('quote_id',qid,'reason','Written confirmed price'),buyer);
 ASSERT r->>'status'='brand_review','Changed commercial terms require brand reapproval';
 PERFORM set_config('request.jwt.claim.role','authenticated',true);PERFORM set_config('request.jwt.claim.sub',test_uuid(3)::text,true);
 r:=public.procurement_command(test_uuid(101),'brand_approve',rid,7,'strict-brand-price');
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 r:=public.procurement_command(test_uuid(101),'office_approve',rid,8,'strict-office','{}',buyer);
 IF r->>'status'='senior_review' THEN
 senior:=buyer||jsonb_build_object('subject_id',test_uuid(9902),'can_senior_approve',true);
 r:=public.procurement_command(test_uuid(101),'senior_approve',rid,(r->>'row_version')::integer,'strict-senior','{}',senior);
 END IF;
 r:=public.procurement_command(test_uuid(101),'issue_po',rid,(r->>'row_version')::integer,'strict-issue',jsonb_build_object('quote_id',qid,'delivery_address','Store address','contact_name','Receiver'),buyer);
 po:=r->'purchase_order';ASSERT po->'commercial_terms'->>'pr_submitted_at' IS NOT NULL;
 doc:=public.procurement_document_data(test_uuid(101),'po',(po->>'id')::uuid,'supplier',buyer);
 ASSERT NOT(doc->'data' ? 'approval_snapshot');ASSERT NOT(doc->'data' ? 'total_amount');
 ASSERT NOT(doc->'data'->'lines'->0 ? 'unit_price');ASSERT NOT(doc->'data'->'lines'->0 ? 'tax_rate_snapshot');
 ASSERT doc->'data'->'lines'->0->>'specification'='A4 pack';
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,%s,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'send_po',po->>'id',po->>'row_version','no-doc','{"evidence_reference":"message"}',buyer),'PROCUREMENT_SUPPLIER_DOCUMENT_REQUIRED');
 path:=test_uuid(101)||'/procurement/po/'||(po->>'id')||'/supplier/'||(doc->>'source_hash')||'/'||repeat('a',64)||'.pdf';
 INSERT INTO storage.objects(bucket_id,name,metadata) VALUES('inventory-purchase-documents',path,'{"size":120,"mimetype":"application/pdf"}');
 PERFORM public.record_procurement_document(test_uuid(101),'po',(po->>'id')::uuid,'supplier',doc->>'source_hash',path,repeat('a',64),120,buyer);
 path:=test_uuid(101)||'/procurement/po/'||(po->>'id')||'/supplier/'||(doc->>'source_hash')||'/'||repeat('b',64)||'.pdf';
 INSERT INTO storage.objects(bucket_id,name,metadata) VALUES('inventory-purchase-documents',path,'{"size":120,"mimetype":"application/pdf"}');
 PERFORM public.record_procurement_document(test_uuid(101),'po',(po->>'id')::uuid,'supplier',doc->>'source_hash',path,repeat('b',64),120,buyer);
 ASSERT (SELECT count(*) FROM public.procurement_document_exports WHERE record_id=(po->>'id')::uuid)=2;
 PERFORM set_config('request.jwt.claim.role','authenticated',true);PERFORM set_config('request.jwt.claim.sub',test_uuid(1)::text,true);
 ASSERT public.can_read_procurement_document(path),'Requester can read a supplier PO';
 ASSERT public.can_read_procurement_document(test_uuid(101)||'/procurement/pr/'||rid||'/internal/test.pdf');
 ASSERT NOT public.can_read_procurement_document(test_uuid(101)||'/procurement/po/'||(po->>'id')||'/internal/test.pdf'),'Requester cannot read a priced internal PO';
 ASSERT NOT public.can_read_procurement_document(test_uuid(102)||'/procurement/po/'||(po->>'id')||'/supplier/test.pdf'),'Foreign-store documents stay private';
 ASSERT public.can_write_procurement_pr_document(test_uuid(101)||'/procurement/pr/'||rid||'/internal/test.pdf');
 ASSERT NOT public.can_write_procurement_pr_document(test_uuid(101)||'/procurement/pr/'||test_uuid(999999)||'/internal/test.pdf');
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 r:=public.procurement_command(test_uuid(101),'send_po',(po->>'id')::uuid,(po->>'row_version')::integer,'strict-send','{"evidence_reference":"Supplier message"}',buyer);
 r:=public.procurement_command(test_uuid(101),'confirm_po',(po->>'id')::uuid,(r->>'row_version')::integer,'strict-confirm',jsonb_build_object('evidence_reference','Accepted terms','terms_hash',po->>'approval_snapshot_hash'),buyer);
 po:=r;
 SELECT id INTO lid FROM public.inventory_purchase_order_lines WHERE purchase_order_id=(po->>'id')::uuid;
 ASSERT (SELECT receipt_classification_snapshot FROM public.inventory_purchase_order_lines WHERE id=lid)='nonstock';
 SELECT current_stock INTO before_stock FROM public.inventory_items WHERE id=test_uuid(501);
 PERFORM set_config('request.jwt.claim.role','authenticated',true);PERFORM set_config('request.jwt.claim.sub',test_uuid(1)::text,true);
 path:=test_uuid(101)||'/'||receipt||'/receipt.pdf';INSERT INTO storage.objects(bucket_id,name,metadata,owner_id) VALUES('inventory-receipt-statements',path,'{"size":120,"mimetype":"application/pdf"}',test_uuid(1)::text);
 payload:=jsonb_build_array(jsonb_build_object('purchase_order_line_id',lid,'received_quantity_base',6,'discrepancy_reason','Split delivery','inspection','{"spec_ok":true,"quality_ok":true,"packaging_ok":true,"expiry_not_applicable":true,"issue_type":"none","photo_paths":[]}'::jsonb));
 r:=public.submit_inventory_receipt_batch((po->>'id')::uuid,receipt,(po->>'row_version')::integer,0,'nonstock-submit',payload,'Receiver',path);
 PERFORM set_config('request.jwt.claim.sub',test_uuid(4)::text,true);
 PERFORM public.verify_inventory_receipt(receipt,(r->>'row_version')::integer,'nonstock-verify');
 ASSERT (SELECT current_stock FROM public.inventory_items WHERE id=test_uuid(501))=before_stock;
 ASSERT NOT EXISTS(SELECT 1 FROM public.inventory_transactions WHERE reference_id=receipt);
 ASSERT (SELECT status FROM public.inventory_receipts WHERE id=receipt)='confirmed';
 SELECT id INTO issue_id FROM public.inventory_receipt_issues WHERE receipt_line_id IN(SELECT id FROM public.inventory_receipt_lines WHERE receipt_id=receipt);
 ASSERT issue_id IS NOT NULL;
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,1,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'resolve_issue',issue_id,'evidence-only','{"resolution":"additional_delivery","reason":"claimed done","evidence_reference":"message"}',buyer),'PROCUREMENT_CONFIRMED_FOLLOWUP_REQUIRED');
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,1,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'resolve_issue',issue_id,'unposted-credit','{"resolution":"credit","reason":"claimed credit","evidence_reference":"message"}',buyer),'PROCUREMENT_POSTED_CREDIT_REQUIRED');
 SELECT to_jsonb(x) INTO po FROM public.inventory_purchase_orders x WHERE id=(po->>'id')::uuid;
 PERFORM set_config('request.jwt.claim.role','authenticated',true);PERFORM set_config('request.jwt.claim.sub',test_uuid(1)::text,true);
 path:=test_uuid(101)||'/'||second_receipt||'/receipt.pdf';INSERT INTO storage.objects(bucket_id,name,metadata,owner_id) VALUES('inventory-receipt-statements',path,'{"size":120,"mimetype":"application/pdf"}',test_uuid(1)::text);
 payload:=jsonb_build_array(jsonb_build_object('purchase_order_line_id',lid,'received_quantity_base',4,'inspection','{"spec_ok":true,"quality_ok":true,"packaging_ok":true,"expiry_not_applicable":true,"issue_type":"none","photo_paths":[]}'::jsonb));
 r:=public.submit_inventory_receipt_batch((po->>'id')::uuid,second_receipt,(po->>'row_version')::integer,0,'nonstock-second',payload,'Receiver',path);
 PERFORM set_config('request.jwt.claim.sub',test_uuid(4)::text,true);
 PERFORM public.verify_inventory_receipt(second_receipt,(r->>'row_version')::integer,'nonstock-second-verify');
 ASSERT (SELECT expected_quantity_base_snapshot FROM public.inventory_receipt_lines WHERE receipt_id=second_receipt)=4;
 ASSERT NOT EXISTS(SELECT 1 FROM public.inventory_receipt_issues WHERE receipt_line_id IN(SELECT id FROM public.inventory_receipt_lines WHERE receipt_id=second_receipt));
 SELECT id INTO followup_id FROM public.inventory_receipt_lines WHERE receipt_id=second_receipt;
 -- Native price readers keep the scoped single snapshot contract.
 ASSERT public.procurement_order_snapshot(test_uuid(101),(po->>'id')::uuid)->'order'->>'id'=po->>'id';
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 data:=public.procurement_workspace_page(test_uuid(101),jsonb_build_object('issue_followup_id',issue_id),buyer);
 ASSERT EXISTS(SELECT 1 FROM jsonb_array_elements(data->'followup_receipt_lines') x WHERE x->>'id'=followup_id::text);
 payload:=jsonb_build_object('resolution','additional_delivery','followup_receipt_line_id',followup_id,'reason','Actually received balance','evidence_reference','Signed receipt');
 r:=public.procurement_command(test_uuid(101),'resolve_issue',issue_id,1,'actual-followup',payload,buyer);
 ASSERT r->>'status'='resolved';ASSERT r->'followup_reference'->>'receipt_line_id'=followup_id::text;
 ASSERT public.procurement_command(test_uuid(101),'resolve_issue',issue_id,1,'actual-followup',payload,buyer)=r;
 SELECT to_jsonb(x) INTO po FROM public.inventory_purchase_orders x WHERE id=(po->>'id')::uuid;
 payment_payload:='{"kind":"advance","paid_by":"employee","amount":50,"external_order_no":"SHOPEE-TEST-1","payment_reference":"ADV-1","evidence_reference":"Actual payment evidence"}';
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,%s,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'record_channel_payment',po->>'id',po->>'row_version','unmapped-employee',payment_payload,buyer),'PROCUREMENT_EMPLOYEE_MAPPING_REQUIRED');
 payment_payload:=payment_payload||jsonb_build_object('office_employee_id',test_uuid(991),'employee_confirmation',jsonb_build_object('employee_id',test_uuid(991),'pos_store_id',test_uuid(101)));
 prior_payment:=public.procurement_command(test_uuid(101),'record_channel_payment',(po->>'id')::uuid,(po->>'row_version')::integer,'actual-advance',payment_payload,buyer);
 ASSERT public.procurement_command(test_uuid(101),'record_channel_payment',(po->>'id')::uuid,(po->>'row_version')::integer,'actual-advance',payment_payload,buyer)=prior_payment;
 po:=prior_payment;
 ASSERT (SELECT count(*) FROM public.procurement_channel_payments WHERE purchase_order_id=(po->>'id')::uuid)=1;
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,%s,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'record_channel_payment',po->>'id',po->>'row_version','overspend',(payment_payload||'{"amount":1000,"payment_reference":"ADV-2"}'::jsonb)::text,buyer),'PROCUREMENT_PREPAYMENT_EXCEEDS_ORDER');
 payment_payload:=payment_payload||jsonb_build_object('advance_payment_id',(SELECT id FROM public.procurement_channel_payments WHERE purchase_order_id=(po->>'id')::uuid AND kind='advance'));
 payment_payload:=payment_payload||'{"kind":"refund","amount":10,"payment_reference":"REF-1"}'::jsonb;
 po:=public.procurement_command(test_uuid(101),'record_channel_payment',(po->>'id')::uuid,(po->>'row_version')::integer,'actual-refund',payment_payload,buyer);
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,%s,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'record_channel_payment',po->>'id',po->>'row_version','over-refund',(payment_payload||'{"amount":500,"payment_reference":"REF-2"}'::jsonb)::text,buyer),'PROCUREMENT_SETTLEMENT_EXCEEDS_ADVANCE');
 payment_payload:=payment_payload||'{"kind":"reimbursement","amount":40,"payment_reference":"REIM-1"}'::jsonb;
 PERFORM public.test_expect_error(format('SELECT public.procurement_command(%L,%L,%L,%s,%L,%L::jsonb,%L::jsonb)',test_uuid(101),'record_channel_payment',po->>'id',po->>'row_version','other-employee',payment_payload||jsonb_build_object('office_employee_id',test_uuid(992),'employee_confirmation',jsonb_build_object('employee_id',test_uuid(992),'pos_store_id',test_uuid(101))),buyer),'PROCUREMENT_ADVANCE_OWNER_REQUIRED');
 po:=public.procurement_command(test_uuid(101),'record_channel_payment',(po->>'id')::uuid,(po->>'row_version')::integer,'actual-reimbursement',payment_payload,buyer);
 PERFORM public.record_procurement_accounting_status(test_uuid(101),jsonb_build_array(jsonb_build_object('purchase_order_id',po->>'id','source_order_version',(po->>'row_version')::integer,'invoice_count',1,'payable_count',1,'held_count',1,'paid_count',0,'reconciliation_required',false,'observed_at',now())));
 data:=public.procurement_workspace_page(test_uuid(101),jsonb_build_object('order_id',po->>'id'),buyer);
 ASSERT data->'order_detail'->'accounting_status'->>'held_count'='1';ASSERT NOT (data->'order_detail'->'accounting_status'->>'stale')::boolean;
 PERFORM set_config('request.jwt.claim.role','authenticated',true);PERFORM set_config('request.jwt.claim.sub',test_uuid(4)::text,true);
 r:=public.procurement_command(test_uuid(101),'return_goods',(po->>'id')::uuid,(po->>'row_version')::integer,'nonstock-return',jsonb_build_object('receipt_line_id',followup_id,'quantity_base',2,'reason','Return unused stationery','evidence_reference','Actual supplier handover'));
 data:=public.procurement_workspace_page(test_uuid(101),jsonb_build_object('order_id',po->>'id'));ASSERT (data->'order_detail'->'accounting_status'->>'stale')::boolean;
 ASSERT (SELECT current_stock FROM public.inventory_items WHERE id=test_uuid(501))=before_stock;
 ASSERT NOT EXISTS(SELECT 1 FROM public.inventory_transactions WHERE reference_type='inventory_supplier_return' AND reference_id=(r->'followup'->>'id')::uuid);
 PERFORM public.test_expect_error(format('INSERT INTO public.inventory_purchase_orders(restaurant_id,supplier_id,purchase_order_no,workflow_version) VALUES(%L,%L,%L,1)',test_uuid(101),test_uuid(201),'legacy-bypass'),'PROCUREMENT_REQUEST_REQUIRED');
 PERFORM set_config('request.jwt.claim.role','service_role',true);
 PERFORM public.test_expect_error('SELECT public.procurement_orders_batch(NULL)','PROCUREMENT_SCOPE_FORBIDDEN');
 PERFORM public.test_expect_error('SELECT public.procurement_snapshots_batch(NULL,NULL)','PROCUREMENT_SCOPE_FORBIDDEN');
 RAISE NOTICE 'PASS: policy snapshots, Adjust/Agree/Approval, changed-price reapproval, requester estimates, supplier allowlist/document gate, nonstock receiving/return, actual split-delivery resolution, prepayment/refund/reimbursement replay and legacy bypass gate';
END $contract$;
ROLLBACK;
