#!/usr/bin/env bash
set -euo pipefail
INTEGRATED_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIRECT_ORDER_CUSTOMER_EXPERIENCE_TEST=1 DIRECT_ORDER_SUPPORT_TEST=1 DIRECT_ORDER_INTEGRATED_TEST=1 DIRECT_ORDER_MONEY_TEST=1 DIRECT_ORDER_PROGRESS_TEST=1 DIRECT_ORDER_REQUIREMENTS_TEST=1 \
  bash "$INTEGRATED_ROOT/test/direct_order_delivery_fallback_sql_test.sh"
