String procurementProcessLabel(String key, String languageCode) {
  final values = {
    "accountingStatus": [
      "Invoice / 채무 / 지급 보류 / 지급 완료",
      "Invoices / payables / held / paid",
      "Hóa đơn / công nợ / giữ / đã trả",
    ],
    "accountingRefresh": [
      "회계 원본 갱신·재대조가 필요합니다.",
      "Refresh and reconcile the accounting source.",
      "Cần cập nhật và đối chiếu lại nguồn kế toán.",
    ],
    "createdFrom": [
      "PR 작성 시작일 (YYYY-MM-DD)",
      "PR created from (YYYY-MM-DD)",
      "Ngày tạo yêu cầu từ (YYYY-MM-DD)",
    ],
    "createdTo": [
      "PR 작성 종료일 (YYYY-MM-DD)",
      "PR created to (YYYY-MM-DD)",
      "Ngày tạo yêu cầu đến (YYYY-MM-DD)",
    ],
    "dateFilterInvalid": [
      "유효한 작성일 범위를 입력하세요.",
      "Enter a valid creation-date range.",
      "Nhập khoảng ngày tạo hợp lệ.",
    ],
    "pauseNew": ["신규 PR 생성 중단", "Pause new PRs", "Tạm dừng yêu cầu mới"],
    "resumeNew": ["신규 PR 생성 재개", "Resume new PRs", "Tiếp tục yêu cầu mới"],
    "legacyReview": [
      "과거 발주 조건 검토",
      "Review historical order terms",
      "Kiểm tra điều kiện đơn cũ",
    ],
    "nextLegacy": [
      "이전 조건 검토",
      "Older terms reviews",
      "Kiểm tra điều kiện trước",
    ],
    "nextIssues": ["이전 차이 이슈", "Older issues", "Vấn đề trước"],
    "nextReturns": ["이전 반품", "Older returns", "Lần trả hàng trước"],
    "nextQuotes": ["이전 견적", "Older quotes", "Báo giá trước"],
    "followupReceipt": [
      "확정된 후속 입고 품목 ID",
      "Confirmed follow-up receipt line ID",
      "ID dòng nhận bổ sung đã xác nhận",
    ],
    "creditJournal": [
      "기장된 차감 분개 ID",
      "Posted supplier credit journal ID",
      "ID bút toán giảm công nợ đã ghi sổ",
    ],
    "notes": ["비고", "Notes", "Ghi chú"],
    "expectedVat": ["예상 VAT", "Estimated VAT", "VAT dự kiến"],
    'activatePolicy': [
      "새 PR부터 매장 조정 → 브랜드 동의 → 구매팀 승인을 적용합니다. 기존 진행 건은 기존 정책을 유지합니다.",
      "New PRs will require store adjustment, brand agreement and purchase approval. Existing requests retain their policy.",
      "Yêu cầu mới cần cửa hàng điều chỉnh, thương hiệu đồng ý và bộ phận mua hàng duyệt. Yêu cầu đang xử lý giữ chính sách cũ.",
    ],
    'company': ["법인", "Company", "Công ty"],
    'employee': ["직원", "Employee", "Nhân viên"],
    'vat': ["VAT (%)", "VAT (%)", "VAT (%)"],
    'baseUnit': ["기본 단위", "Base unit", "Đơn vị cơ sở"],
    'expectedTotal': [
      "예상 합계 (VAT 포함)",
      "Estimated total including VAT",
      "Tổng dự kiến gồm VAT",
    ],
    'searchRecords': ["PR·PO 검색", "Search PR / PO", "Tìm yêu cầu / đơn mua"],
    'nextEvents': ["다음 이력", "More history", "Lịch sử tiếp theo"],
    'nextReceipts': ["이전 입고", "Older receipts", "Đợt nhận trước"],
    'paymentHold': [
      "선결제 대조 후 지급 보류 해제",
      "Reconcile prepayment before releasing payment",
      "Đối chiếu trả trước trước khi bỏ giữ thanh toán",
    ],
    "brand_review": ["브랜드 검토 대기", "Brand review", "Chờ thương hiệu duyệt"],
    "brand_approve": ["브랜드 동의", "Brand agreement", "Thương hiệu đồng ý"],
    "adjust_request": ["수량 조정", "Adjust quantities", "Điều chỉnh số lượng"],
    "cancel_request": ["요청 취소", "Cancel request", "Hủy yêu cầu"],
    "category": ["구매 유형", "Purchase category", "Loại mua hàng"],
    "channel": ["구매 채널", "Purchase channel", "Kênh mua hàng"],
    "raw_material": ["원재료", "Raw materials", "Nguyên vật liệu"],
    "tools": ["도구·비품", "Tools and equipment", "Công cụ dụng cụ"],
    "stationery": ["사무용품", "Stationery", "Văn phòng phẩm"],
    "other": ["기타", "Other", "Khác"],
    "ordinary": ["일반 구매", "Standard purchase", "Mua thông thường"],
    "shopee": ["Shopee", "Shopee", "Shopee"],
    "estimate": ["예상 단가", "Estimated unit price", "Đơn giá dự kiến"],
    "supplierPdf": [
      "업체용 PO PDF",
      "Supplier PO PDF",
      "PDF đơn mua cho nhà cung cấp",
    ],
    "internalPdf": ["내부용 PO PDF", "Internal PO PDF", "PDF đơn mua nội bộ"],
    "prPdf": ["PR PDF", "PR PDF", "PDF yêu cầu mua"],
    "nextRequests": ["다음 요청", "Next requests", "Yêu cầu tiếp theo"],
    "nextOrders": ["다음 발주", "Next orders", "Đơn mua tiếp theo"],
    "firstPage": ["처음으로", "First page", "Trang đầu"],
    "details": ["상세 보기", "View details", "Xem chi tiết"],
    "searchCatalog": ["품목 검색", "Search catalog", "Tìm mặt hàng"],
    "moreCatalog": ["다음 품목", "More catalog items", "Thêm mặt hàng"],
    "dates": [
      "작성 {0} · 제출 {1} · PO 발행 {2}",
      "Created {0} · submitted {1} · PO issued {2}",
      "Tạo {0} · gửi {1} · phát hành đơn {2}",
    ],
    "specification": ["규격", "Specification", "Quy cách"],
    "stock": ["재고", "Stock", "Tồn kho"],
    "nonstock": ["비재고", "Nonstock", "Không nhập kho"],
    "asset": ["자산", "Asset", "Tài sản"],
    "reason": ["사유", "Reason", "Lý do"],
    "quantity": ["수량", "Quantity", "Số lượng"],
    "item": ["품목", "Item", "Mặt hàng"],
    "unit": ["단위", "Unit", "Đơn vị"],
    "amount": ["금액", "Amount", "Số tiền"],
    "titlePr": ["구매요청서", "Purchase request", "Phiếu yêu cầu mua hàng"],
    "titlePo": ["발주서", "Purchase order", "Đơn đặt hàng"],
    "approveStore": [
      "매장 조정·승인",
      "Store adjustment and approval",
      "Cửa hàng điều chỉnh và duyệt",
    ],
    "approveBrand": ["브랜드 동의", "Brand agreement", "Thương hiệu đồng ý"],
    "approvePurchase": [
      "구매팀 승인",
      "Purchase approval",
      "Bộ phận mua hàng duyệt",
    ],
    "catalogSetup": [
      "구매 품목 등록",
      "Set up purchase item",
      "Thiết lập mặt hàng mua",
    ],
    "productCode": ["품목 코드", "Item code", "Mã mặt hàng"],
    "receiptClass": [
      "입고 분류",
      "Receiving classification",
      "Phân loại nhập hàng",
    ],
    "factor": [
      "재고 단위당 기본 수량",
      "Base quantity per stock unit",
      "Lượng cơ sở mỗi đơn vị kho",
    ],
    "channelRecord": [
      "Shopee 주문·선결제 기록",
      "Shopee order / prepayment record",
      "Ghi đơn Shopee / trả trước",
    ],
    "externalOrder": ["Shopee 주문번호", "Shopee order number", "Mã đơn Shopee"],
    "paymentEvidence": [
      "결제·환불 증빙",
      "Payment / refund evidence",
      "Chứng từ thanh toán / hoàn tiền",
    ],
    "paymentReference": [
      "Office 지급·정산 참조번호",
      "Office payment / settlement reference",
      "Mã chi / quyết toán Office",
    ],
    "channelKind": ["기록 유형", "Record type", "Loại ghi nhận"],
    "advance": ["선결제", "Prepayment", "Trả trước"],
    "refund": ["환불", "Refund", "Hoàn tiền"],
    "reimbursement": ["직원 정산", "Employee reimbursement", "Hoàn ứng nhân viên"],
    "operatingMetrics": [
      "구매 운영 지표·담당자",
      "Procurement metrics / responsibility",
      "Chỉ số mua hàng / người phụ trách",
    ],
    "storeWaiting": ["매장 검토 대기", "Awaiting store review", "Chờ cửa hàng duyệt"],
    "brandWaiting": [
      "브랜드 검토 대기",
      "Awaiting brand review",
      "Chờ thương hiệu duyệt",
    ],
    "purchaseWaiting": [
      "구매 승인 대기",
      "Awaiting purchase approval",
      "Chờ duyệt mua hàng",
    ],
    "waitingP95": [
      "미결 승인 대기시간 p95 (시간)",
      "Open approval age p95 (hours)",
      "Thời gian chờ duyệt p95 (giờ)",
    ],
    "supplierDocuments": [
      "업체용 PO 파일 등록 건",
      "POs with supplier documents",
      "Đơn mua có tệp gửi nhà cung cấp",
    ],
    "accountingHolds": [
      "회계 보류·대조 필요 PO",
      "POs held / requiring reconciliation",
      "Đơn mua tạm giữ / cần đối chiếu",
    ],
    "inspectionWaiting": [
      "제출된 입고 검증 대기",
      "Submitted receipts awaiting verification",
      "Phiếu nhập đã nộp chờ xác minh",
    ],
    "openIssues": [
      "미결 입고 차이",
      "Open receiving issues",
      "Chênh lệch nhập hàng chưa xử lý",
    ],
    "missingRoles": [
      "유효 담당자 미지정 단계",
      "Stages missing current assignments",
      "Bước chưa có người phụ trách hiệu lực",
    ],
    "assignPrincipal": [
      "담당자·대리자 계정 연결",
      "Link responsible / deputy account",
      "Liên kết tài khoản phụ trách / thay thế",
    ],
    "principalSystem": [
      "계정 시스템 (pos / office)",
      "Account system (pos / office)",
      "Hệ thống tài khoản (pos / office)",
    ],
    "principalSubject": [
      "기존 인증 계정 UUID",
      "Existing authentication account UUID",
      "UUID tài khoản xác thực hiện có",
    ],
    "workforcePerson": [
      "Office 직원 UUID (동일인 기준)",
      "Office employee UUID (person identity)",
      "UUID nhân viên Office (định danh cá nhân)",
    ],
    "principalStage": [
      "단계 (requester/store/brand/purchase/receiver/verifier/finance)",
      "Stage (requester/store/brand/purchase/receiver/verifier/finance)",
      "Bước (requester/store/brand/purchase/receiver/verifier/finance)",
    ],
    "validFrom": [
      "효력 시작 (시간대 포함 ISO 일시)",
      "Valid from (ISO timestamp with timezone)",
      "Hiệu lực từ (ISO có múi giờ)",
    ],
    "validUntil": [
      "효력 종료 (시간대 포함 ISO 일시)",
      "Valid until (ISO timestamp with timezone)",
      "Hiệu lực đến (ISO có múi giờ)",
    ],
    "assignmentReason": [
      "담당·대리 배정 사유",
      "Responsibility / deputy assignment reason",
      "Lý do phân công / thay thế",
    ],
    "role_requester": ["요청자", "Requester", "Người yêu cầu"],
    "role_store": ["매장관리자", "Store Manager", "Quản lý cửa hàng"],
    "role_brand": ["브랜드매니저", "Brand Manager", "Quản lý thương hiệu"],
    "role_purchase": ["구매팀", "Purchasing", "Bộ phận mua hàng"],
    "role_receiver": [
      "수령·검수자",
      "Receiver / inspector",
      "Người nhận / kiểm tra",
    ],
    "role_verifier": ["입고 검증자", "Receipt verifier", "Người xác minh nhập hàng"],
    "role_finance": ["회계·지급", "Accounting / payments", "Kế toán / thanh toán"],
  };
  return values[key]?[languageCode == 'ko'
          ? 0
          : languageCode == 'vi'
          ? 2
          : 1] ??
      key;
}
