DO $$ BEGIN
 IF (SELECT count(*) FROM pg_trigger WHERE (tgrelid='public.inventory_receipts'::regclass AND tgname='inventory_receipt_header_change_guard' OR tgrelid='public.inventory_receipt_lines'::regclass AND tgname='inventory_receipt_line_change_guard') AND NOT tgisinternal AND tgenabled='O')<>2 THEN RAISE EXCEPTION 'BUNSIK_RECEIPT_GUARDS_NOT_ENABLED'; END IF;
 IF (SELECT count(*) FROM public.inventory_products WHERE restaurant_id='8bc9eef5-dcd5-46b1-b931-23f77132322c')<>123 OR (SELECT count(*) FROM public.inventory_products WHERE restaurant_id='3a268807-771f-4fd4-84fe-e1b0b00de40a')<>123 THEN RAISE EXCEPTION 'BUNSIK_FINAL_COUNT_INVALID'; END IF;
 IF EXISTS(SELECT 1 FROM public.inventory_products b FULL JOIN public.inventory_products s ON s.restaurant_id='3a268807-771f-4fd4-84fe-e1b0b00de40a' AND s.product_code=b.product_code WHERE b.restaurant_id='8bc9eef5-dcd5-46b1-b931-23f77132322c' AND (s.id IS NULL OR (to_jsonb(b)-ARRAY['id','restaurant_id','inventory_item_id','created_at','updated_at']) IS DISTINCT FROM (to_jsonb(s)-ARRAY['id','restaurant_id','inventory_item_id','created_at','updated_at']))) THEN RAISE EXCEPTION 'BUNSIK_CLONE_PRODUCT_MISMATCH'; END IF;
 IF EXISTS(SELECT 1 FROM public.inventory_products b JOIN public.inventory_products s ON s.restaurant_id='3a268807-771f-4fd4-84fe-e1b0b00de40a' AND s.product_code=b.product_code JOIN public.inventory_items bi ON bi.id=b.inventory_item_id JOIN public.inventory_items si ON si.id=s.inventory_item_id WHERE b.restaurant_id='8bc9eef5-dcd5-46b1-b931-23f77132322c' AND (to_jsonb(bi)-ARRAY['id','restaurant_id','created_at','updated_at']) IS DISTINCT FROM (to_jsonb(si)-ARRAY['id','restaurant_id','created_at','updated_at'])) THEN RAISE EXCEPTION 'BUNSIK_CLONE_STOCK_MISMATCH'; END IF;
 IF EXISTS(SELECT 1 FROM public.inventory_products b JOIN public.inventory_products s ON s.restaurant_id='3a268807-771f-4fd4-84fe-e1b0b00de40a' AND s.product_code=b.product_code WHERE b.restaurant_id='8bc9eef5-dcd5-46b1-b931-23f77132322c' AND (SELECT coalesce(jsonb_agg(to_jsonb(x)-ARRAY['id','product_id','created_at','updated_at'] ORDER BY supplier_id,order_unit),'[]') FROM public.inventory_supplier_items x WHERE x.product_id=b.id) IS DISTINCT FROM (SELECT coalesce(jsonb_agg(to_jsonb(x)-ARRAY['id','product_id','created_at','updated_at'] ORDER BY supplier_id,order_unit),'[]') FROM public.inventory_supplier_items x WHERE x.product_id=s.id)) THEN RAISE EXCEPTION 'BUNSIK_CLONE_SUPPLIER_MISMATCH'; END IF;
 IF EXISTS(SELECT 1 FROM inventory_migration_backup.bunsik_20260930 z CROSS JOIN LATERAL jsonb_populate_recordset(NULL::public.inventory_items,z.rows) old JOIN public.inventory_items i ON i.id=old.id WHERE z.table_name='binh_items' AND to_jsonb(old) IS DISTINCT FROM to_jsonb(i)) THEN RAISE EXCEPTION 'BUNSIK_ORIGINAL_STOCK_CHANGED'; END IF;
 IF EXISTS(SELECT 1 FROM public.inventory_products WHERE restaurant_id IN ('8bc9eef5-dcd5-46b1-b931-23f77132322c','3a268807-771f-4fd4-84fe-e1b0b00de40a') AND product_code !~ '^(WR|OT|YK|SP|PL|MB|NK|DR|GO)[0-9]{3}$') THEN RAISE EXCEPTION 'BUNSIK_FINAL_CODE_INVALID'; END IF;
END $$;
