-- =============================================================================
-- Phase 2 Step 5 — RPC enum fixes
-- Migration: 20260412210000_phase_2_step_5_rpc_enum_fixes.sql
-- Companion to: 20260412200000_phase_2_step_5_existing_table_extensions.sql
--
-- Fixes two RPCs broken by Step 5 schema changes:
--
-- add_items_to_order:
--   BEFORE: INSERT item_type = 'standard'  → violates new CHECK('menu_item','service_charge')
--           INSERT missing display_name    → violates NOT NULL
--   AFTER:  item_type = 'menu_item', display_name = m.name
--
-- process_payment:
--   BEFORE: validates p_method IN ('cash','card','pay','service')
--           v_is_revenue := (p_method <> 'service')
--           INSERT missing amount_portion  → violates NOT NULL
--   AFTER:  validates p_method IN WeTax sendOrderInfo enum
--           v_is_revenue := TRUE (service charge is now an order_item line)
--           INSERT amount_portion = p_amount
-- =============================================================================

-- (Applied directly via Supabase MCP apply_migration — see session log)
-- Full SQL bodies recorded here for migration chain completeness.

-- add_items_to_order: item_type 'standard'→'menu_item', add display_name
-- process_payment: WeTax method enum, is_revenue=TRUE, add amount_portion
