-- Authoritative Photo Objet scheduler expectations. This ledger is independent
-- from Moers raw sales and is generated by its database owner without changing
-- immutable sales history.

CREATE TABLE IF NOT EXISTS public.photo_slot_20260713120000_state (
  migration_id text PRIMARY KEY,
  prior_health_function_existed boolean,
  prior_health_view_existed boolean,
  prior_health_function_definition text,
  pull_run_interval_rows_existed boolean,
  pull_run_interval_rows_data_type text,
  pull_run_interval_rows_not_null boolean,
  pull_run_interval_rows_default text,
  pull_run_interval_rows_comment text,
  pull_run_interval_rows_constraint_existed boolean,
  pull_run_interval_rows_constraint_definition text,
  captured_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.photo_slot_20260713120000_state
  ADD COLUMN IF NOT EXISTS prior_health_function_existed boolean,
  ADD COLUMN IF NOT EXISTS prior_health_view_existed boolean,
  ADD COLUMN IF NOT EXISTS pull_run_interval_rows_existed boolean,
  ADD COLUMN IF NOT EXISTS pull_run_interval_rows_data_type text,
  ADD COLUMN IF NOT EXISTS pull_run_interval_rows_not_null boolean,
  ADD COLUMN IF NOT EXISTS pull_run_interval_rows_default text,
  ADD COLUMN IF NOT EXISTS pull_run_interval_rows_comment text,
  ADD COLUMN IF NOT EXISTS pull_run_interval_rows_constraint_existed boolean,
  ADD COLUMN IF NOT EXISTS pull_run_interval_rows_constraint_definition text;

INSERT INTO public.photo_slot_20260713120000_state (
  migration_id,
  prior_health_function_existed,
  prior_health_view_existed,
  prior_health_function_definition,
  pull_run_interval_rows_existed,
  pull_run_interval_rows_data_type,
  pull_run_interval_rows_not_null,
  pull_run_interval_rows_default,
  pull_run_interval_rows_comment,
  pull_run_interval_rows_constraint_existed,
  pull_run_interval_rows_constraint_definition
)
SELECT
  '20260713120000',
  to_regprocedure(
    'public.photo_objet_collection_health_at(timestamp with time zone)'
  ) IS NOT NULL,
  to_regclass('public.v_photo_objet_collection_health') IS NOT NULL,
  pg_get_functiondef(
    to_regprocedure(
      'public.photo_objet_collection_health_at(timestamp with time zone)'
    )
  ),
  EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.photo_objet_sales_pull_runs'::regclass
      AND attname = 'interval_rows' AND NOT attisdropped
  ),
  (
    SELECT format_type(a.atttypid, a.atttypmod)
    FROM pg_attribute a
    WHERE a.attrelid = 'public.photo_objet_sales_pull_runs'::regclass
      AND a.attname = 'interval_rows' AND NOT a.attisdropped
  ),
  (
    SELECT a.attnotnull
    FROM pg_attribute a
    WHERE a.attrelid = 'public.photo_objet_sales_pull_runs'::regclass
      AND a.attname = 'interval_rows' AND NOT a.attisdropped
  ),
  (
    SELECT pg_get_expr(d.adbin, d.adrelid)
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = 'public.photo_objet_sales_pull_runs'::regclass
      AND a.attname = 'interval_rows' AND NOT a.attisdropped
  ),
  (
    SELECT col_description(a.attrelid, a.attnum)
    FROM pg_attribute a
    WHERE a.attrelid = 'public.photo_objet_sales_pull_runs'::regclass
      AND a.attname = 'interval_rows' AND NOT a.attisdropped
  ),
  EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.photo_objet_sales_pull_runs'::regclass
      AND conname = 'photo_objet_pull_run_interval_rows_check'
  ),
  (
    SELECT pg_get_constraintdef(c.oid, true)
    FROM pg_constraint c
    WHERE c.conrelid = 'public.photo_objet_sales_pull_runs'::regclass
      AND c.conname = 'photo_objet_pull_run_interval_rows_check'
  )
ON CONFLICT (migration_id) DO NOTHING;

ALTER TABLE public.photo_slot_20260713120000_state
  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photo_slot_20260713120000_state
  FORCE ROW LEVEL SECURITY;

REVOKE ALL ON public.photo_slot_20260713120000_state
  FROM PUBLIC, anon, authenticated, service_role;

ALTER TABLE public.photo_objet_sales_pull_runs
  ADD COLUMN IF NOT EXISTS interval_rows integer;

DO $$
DECLARE
  v_data_type text;
  v_constraint_definition text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod) INTO v_data_type
  FROM pg_attribute a
  WHERE a.attrelid = 'public.photo_objet_sales_pull_runs'::regclass
    AND a.attname = 'interval_rows' AND NOT a.attisdropped;
  IF v_data_type <> 'integer' THEN
    RAISE EXCEPTION 'PHOTO_SLOT_INTERVAL_ROWS_TYPE_INCOMPATIBLE: %', v_data_type;
  END IF;

  SELECT pg_get_constraintdef(c.oid, true) INTO v_constraint_definition
  FROM pg_constraint c
  WHERE c.conrelid = 'public.photo_objet_sales_pull_runs'::regclass
    AND c.conname = 'photo_objet_pull_run_interval_rows_check';
  IF v_constraint_definition IS NOT NULL
     AND v_constraint_definition <> 'CHECK (interval_rows IS NULL OR interval_rows >= 0)' THEN
    RAISE EXCEPTION 'PHOTO_SLOT_INTERVAL_ROWS_CONSTRAINT_INCOMPATIBLE: %',
      v_constraint_definition;
  END IF;
  IF v_constraint_definition IS NULL THEN
    ALTER TABLE public.photo_objet_sales_pull_runs
      ADD CONSTRAINT photo_objet_pull_run_interval_rows_check
      CHECK (interval_rows IS NULL OR interval_rows >= 0);
  END IF;
END $$;

COMMENT ON COLUMN public.photo_objet_sales_pull_runs.interval_rows IS
  'Rows selected inside this exact typed interval; independent from daily aggregate device count.';

CREATE TABLE IF NOT EXISTS public.photo_objet_monitoring_policies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES public.restaurants(id) ON DELETE RESTRICT,
  effective_from timestamptz NOT NULL,
  effective_to timestamptz,
  timezone text NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  schedule_version text NOT NULL DEFAULT 'hcm-two-hour-v1',
  grace_minutes integer NOT NULL DEFAULT 90,
  final_slot_grace_minutes integer NOT NULL DEFAULT 90,
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT photo_objet_monitoring_policy_period_check
    CHECK (effective_to IS NULL OR effective_to > effective_from),
  CONSTRAINT photo_objet_monitoring_policy_timezone_check
    CHECK (timezone = 'Asia/Ho_Chi_Minh'),
  CONSTRAINT photo_objet_monitoring_policy_schedule_check
    CHECK (schedule_version = 'hcm-two-hour-v1'),
  CONSTRAINT photo_objet_monitoring_policy_grace_check
    CHECK (grace_minutes BETWEEN 0 AND 180),
  CONSTRAINT photo_objet_monitoring_policy_final_grace_check
    CHECK (final_slot_grace_minutes BETWEEN 0 AND 180),
  UNIQUE (store_id, effective_from)
);

CREATE UNIQUE INDEX IF NOT EXISTS photo_objet_monitoring_policy_one_open_idx
  ON public.photo_objet_monitoring_policies (store_id)
  WHERE effective_to IS NULL;

CREATE OR REPLACE FUNCTION public.enforce_photo_objet_monitoring_policy_period()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.photo_objet_monitoring_policies existing
    WHERE existing.store_id = NEW.store_id
      AND existing.id <> NEW.id
      AND (TG_OP <> 'INSERT' OR existing.effective_from <> NEW.effective_from)
      AND tstzrange(existing.effective_from, existing.effective_to, '[)')
        && tstzrange(NEW.effective_from, NEW.effective_to, '[)')
  ) THEN
    RAISE EXCEPTION 'PHOTO_MONITORING_POLICY_PERIOD_OVERLAP';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_photo_objet_monitoring_policy_period
  ON public.photo_objet_monitoring_policies;
CREATE TRIGGER trg_photo_objet_monitoring_policy_period
BEFORE INSERT OR UPDATE ON public.photo_objet_monitoring_policies
FOR EACH ROW EXECUTE FUNCTION public.enforce_photo_objet_monitoring_policy_period();

CREATE TABLE IF NOT EXISTS public.photo_objet_expected_slots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES public.restaurants(id) ON DELETE RESTRICT,
  slot_date_hcm date NOT NULL,
  slot_time_hcm time NOT NULL,
  scheduled_at timestamptz NOT NULL,
  due_at timestamptz NOT NULL,
  monitoring_policy_id uuid NOT NULL
    REFERENCES public.photo_objet_monitoring_policies(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'expected',
  successful_run_id uuid REFERENCES public.photo_objet_sales_pull_runs(id)
    ON DELETE SET NULL,
  attempt_count integer NOT NULL DEFAULT 0,
  last_failure_class text,
  alerted_failure_class text,
  alerted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT photo_objet_expected_slot_status_check CHECK (
    status IN (
      'expected', 'running', 'collected', 'collected_zero',
      'missing', 'failed', 'recovered'
    )
  ),
  CONSTRAINT photo_objet_expected_slot_failure_check CHECK (
    last_failure_class IS NULL OR last_failure_class IN (
      'COLLECTION_FAILED', 'SLOT_MISSING', 'DATA_INCOMPLETE'
    )
  ),
  CONSTRAINT photo_objet_expected_slot_alert_check CHECK (
    alerted_failure_class IS NULL OR alerted_failure_class IN (
      'COLLECTION_FAILED', 'SLOT_MISSING', 'DATA_INCOMPLETE'
    )
  ),
  CONSTRAINT photo_objet_expected_slot_time_check CHECK (
    slot_time_hcm IN (
      TIME '10:00', TIME '12:00', TIME '14:00', TIME '16:00',
      TIME '18:00', TIME '20:00', TIME '23:00'
    )
  ),
  CONSTRAINT photo_objet_expected_slot_due_check CHECK (due_at >= scheduled_at),
  CONSTRAINT photo_objet_expected_slot_attempt_check CHECK (attempt_count >= 0),
  UNIQUE (store_id, slot_date_hcm, slot_time_hcm)
);

CREATE INDEX IF NOT EXISTS photo_objet_expected_slots_due_idx
  ON public.photo_objet_expected_slots (due_at, status);
CREATE INDEX IF NOT EXISTS photo_objet_expected_slots_policy_idx
  ON public.photo_objet_expected_slots (monitoring_policy_id, slot_date_hcm);

ALTER TABLE public.photo_objet_monitoring_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photo_objet_monitoring_policies FORCE ROW LEVEL SECURITY;
ALTER TABLE public.photo_objet_expected_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photo_objet_expected_slots FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS photo_objet_monitoring_policies_store_read
  ON public.photo_objet_monitoring_policies;
CREATE POLICY photo_objet_monitoring_policies_store_read
ON public.photo_objet_monitoring_policies FOR SELECT TO authenticated
USING (
  public.is_super_admin()
  OR EXISTS (
    SELECT 1 FROM public.user_accessible_stores(auth.uid()) s(store_id)
    WHERE s.store_id = photo_objet_monitoring_policies.store_id
  )
);

DROP POLICY IF EXISTS photo_objet_expected_slots_store_read
  ON public.photo_objet_expected_slots;
CREATE POLICY photo_objet_expected_slots_store_read
ON public.photo_objet_expected_slots FOR SELECT TO authenticated
USING (
  public.is_super_admin()
  OR EXISTS (
    SELECT 1 FROM public.user_accessible_stores(auth.uid()) s(store_id)
    WHERE s.store_id = photo_objet_expected_slots.store_id
  )
);

REVOKE ALL ON public.photo_objet_monitoring_policies
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON public.photo_objet_expected_slots
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.photo_objet_monitoring_policies TO authenticated;
GRANT SELECT ON public.photo_objet_expected_slots TO authenticated;
GRANT SELECT ON public.photo_objet_monitoring_policies TO service_role;
GRANT SELECT ON public.photo_objet_expected_slots TO service_role;

-- Policies are deliberately not inferred from brand membership. Operations
-- must insert the explicitly approved store mappings and effective timestamp;
-- this keeps inactive, deleted, and environment-disabled stores out.

CREATE OR REPLACE FUNCTION public.photo_objet_ensure_expected_slots(
  p_from_date date,
  p_to_date date
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_inserted integer;
BEGIN
  IF p_from_date IS NULL OR p_to_date IS NULL OR p_to_date < p_from_date THEN
    RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_DATE_RANGE_INVALID';
  END IF;
  IF p_to_date - p_from_date > 92 THEN
    RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_DATE_RANGE_TOO_LARGE';
  END IF;

  WITH target_dates AS (
    SELECT generate_series(p_from_date, p_to_date, interval '1 day')::date AS slot_date
  ),
  slot_times(slot_time) AS (
    VALUES
      (TIME '10:00'), (TIME '12:00'), (TIME '14:00'), (TIME '16:00'),
      (TIME '18:00'), (TIME '20:00'), (TIME '23:00')
  ),
  candidates AS (
    SELECT
      p.id AS policy_id,
      p.store_id,
      d.slot_date,
      st.slot_time,
      (d.slot_date + st.slot_time) AT TIME ZONE p.timezone AS scheduled_at,
      CASE
        WHEN st.slot_time = TIME '23:00' THEN
          (d.slot_date + st.slot_time) AT TIME ZONE p.timezone
            + make_interval(mins => p.final_slot_grace_minutes)
        ELSE
          (d.slot_date + st.slot_time) AT TIME ZONE p.timezone
            + make_interval(mins => p.grace_minutes)
      END AS due_at
    FROM public.photo_objet_monitoring_policies p
    JOIN public.restaurants r ON r.id = p.store_id AND r.is_active = true
    CROSS JOIN target_dates d
    CROSS JOIN slot_times st
    WHERE p.is_enabled = true
      AND (d.slot_date + st.slot_time) AT TIME ZONE p.timezone >= p.effective_from
      AND (
        p.effective_to IS NULL
        OR (d.slot_date + st.slot_time) AT TIME ZONE p.timezone < p.effective_to
      )
  )
  INSERT INTO public.photo_objet_expected_slots (
    store_id, slot_date_hcm, slot_time_hcm, scheduled_at, due_at,
    monitoring_policy_id
  )
  SELECT store_id, slot_date, slot_time, scheduled_at, due_at, policy_id
  FROM candidates
  ON CONFLICT (store_id, slot_date_hcm, slot_time_hcm) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  RETURN v_inserted;
END;
$$;

CREATE OR REPLACE FUNCTION public.photo_objet_claim_expected_slot(
  p_store_id uuid,
  p_slot_date_hcm date,
  p_slot_time_hcm time,
  p_run_id uuid
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE v_status text;
BEGIN
  UPDATE public.photo_objet_expected_slots
  SET status = CASE
        WHEN status IN ('collected', 'collected_zero', 'recovered') THEN status
        ELSE 'running'
      END,
      attempt_count = attempt_count + 1,
      updated_at = now()
  WHERE store_id = p_store_id
    AND slot_date_hcm = p_slot_date_hcm
    AND slot_time_hcm = p_slot_time_hcm
  RETURNING status INTO v_status;

  IF NOT FOUND THEN RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_NOT_FOUND'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.photo_objet_sales_pull_runs
    WHERE id = p_run_id AND store_id = p_store_id
      AND run_source = 'scheduled'
      AND slot_date_hcm = p_slot_date_hcm
      AND slot_time_hcm = p_slot_time_hcm
  ) THEN
    RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_RUN_IDENTITY_MISMATCH';
  END IF;
  RETURN v_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.photo_objet_complete_expected_slot(
  p_store_id uuid,
  p_slot_date_hcm date,
  p_slot_time_hcm time,
  p_run_id uuid,
  p_zero_sales boolean
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE v_status text;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.photo_objet_sales_pull_runs
    WHERE id = p_run_id AND store_id = p_store_id
      AND run_source = 'scheduled' AND status = 'success'
      AND slot_date_hcm = p_slot_date_hcm
      AND slot_time_hcm = p_slot_time_hcm
  ) THEN
    RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_SUCCESS_RUN_MISMATCH';
  END IF;

  UPDATE public.photo_objet_expected_slots
  SET status = CASE
        WHEN status IN ('collected', 'collected_zero', 'recovered') THEN status
        WHEN status IN ('missing', 'failed') THEN 'recovered'
        WHEN p_zero_sales THEN 'collected_zero'
        ELSE 'collected'
      END,
      successful_run_id = COALESCE(successful_run_id, p_run_id),
      last_failure_class = CASE
        WHEN status IN ('missing', 'failed') THEN last_failure_class
        ELSE NULL
      END,
      updated_at = now()
  WHERE store_id = p_store_id
    AND slot_date_hcm = p_slot_date_hcm
    AND slot_time_hcm = p_slot_time_hcm
  RETURNING status INTO v_status;
  IF NOT FOUND THEN RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_NOT_FOUND'; END IF;
  RETURN v_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.photo_objet_fail_expected_slot(
  p_store_id uuid,
  p_slot_date_hcm date,
  p_slot_time_hcm time,
  p_failure_class text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE v_status text;
BEGIN
  IF p_failure_class NOT IN ('COLLECTION_FAILED', 'DATA_INCOMPLETE') THEN
    RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_FAILURE_CLASS_INVALID';
  END IF;
  UPDATE public.photo_objet_expected_slots
  SET status = CASE
        WHEN status IN ('collected', 'collected_zero', 'recovered') THEN status
        ELSE 'failed'
      END,
      last_failure_class = CASE
        WHEN status IN ('collected', 'collected_zero', 'recovered') THEN last_failure_class
        ELSE p_failure_class
      END,
      updated_at = now()
  WHERE store_id = p_store_id
    AND slot_date_hcm = p_slot_date_hcm
    AND slot_time_hcm = p_slot_time_hcm
  RETURNING status INTO v_status;
  IF NOT FOUND THEN RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_NOT_FOUND'; END IF;
  RETURN v_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.photo_objet_refresh_expected_slot_health(
  p_observed_at timestamptz DEFAULT now(),
  p_lookback_days integer DEFAULT 2
)
RETURNS TABLE (
  store_id uuid,
  slot_date_hcm date,
  slot_time_hcm time,
  status text,
  failure_class text,
  due_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_today date := (p_observed_at AT TIME ZONE 'Asia/Ho_Chi_Minh')::date;
BEGIN
  IF p_lookback_days < 1 OR p_lookback_days > 31 THEN
    RAISE EXCEPTION 'PHOTO_EXPECTED_SLOT_LOOKBACK_INVALID';
  END IF;

  -- Reconcile by exact typed identity only. A later run can never cover an
  -- earlier slot, and manual/backfill runs never alter scheduler history.
  WITH successful_runs AS (
    SELECT DISTINCT ON (r.store_id, r.slot_date_hcm, r.slot_time_hcm)
      r.store_id, r.slot_date_hcm, r.slot_time_hcm, r.id,
      r.interval_rows = 0 AS zero_sales
    FROM public.photo_objet_sales_pull_runs r
    WHERE r.run_source = 'scheduled'
      AND r.status = 'success'
      AND r.slot_date_hcm IS NOT NULL
      AND r.slot_time_hcm IS NOT NULL
      AND r.interval_rows IS NOT NULL
    ORDER BY r.store_id, r.slot_date_hcm, r.slot_time_hcm, r.finished_at, r.id
  )
  UPDATE public.photo_objet_expected_slots s
  SET status = CASE
        WHEN s.status IN ('missing', 'failed') THEN 'recovered'
        WHEN sr.zero_sales THEN 'collected_zero'
        ELSE 'collected'
      END,
      successful_run_id = COALESCE(s.successful_run_id, sr.id),
      updated_at = now()
  FROM successful_runs sr
  WHERE s.store_id = sr.store_id
    AND s.slot_date_hcm = sr.slot_date_hcm
    AND s.slot_time_hcm = sr.slot_time_hcm
    AND s.status NOT IN ('collected', 'collected_zero', 'recovered');

  UPDATE public.photo_objet_expected_slots s
  SET status = 'missing',
      last_failure_class = 'SLOT_MISSING',
      updated_at = now()
  WHERE s.due_at <= p_observed_at
    AND s.status IN ('expected', 'running');

  RETURN QUERY
  SELECT s.store_id, s.slot_date_hcm, s.slot_time_hcm, s.status,
    s.last_failure_class, s.due_at
  FROM public.photo_objet_expected_slots s
  WHERE s.due_at <= p_observed_at
    AND s.status IN ('missing', 'failed')
    AND s.last_failure_class IS NOT NULL
    AND s.alerted_failure_class IS DISTINCT FROM s.last_failure_class;
END;
$$;

CREATE OR REPLACE FUNCTION public.photo_objet_ack_expected_slot_alert(
  p_store_id uuid,
  p_slot_date_hcm date,
  p_slot_time_hcm time,
  p_failure_class text,
  p_alerted_at timestamptz DEFAULT now()
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  UPDATE public.photo_objet_expected_slots s
  SET alerted_failure_class = p_failure_class,
      alerted_at = p_alerted_at,
      updated_at = now()
  WHERE s.store_id = p_store_id
    AND s.slot_date_hcm = p_slot_date_hcm
    AND s.slot_time_hcm = p_slot_time_hcm
    AND s.status IN ('missing', 'failed')
    AND s.last_failure_class = p_failure_class;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.photo_objet_expected_slot_health_at(
  p_observed_at timestamptz DEFAULT now(),
  p_lookback_days integer DEFAULT 2
)
RETURNS TABLE (
  store_id uuid,
  target_date date,
  policy_expected_slots integer,
  materialized_slots integer,
  coverage_missing_slots integer,
  policy_store_active boolean,
  due_slots integer,
  collected_slots integer,
  collected_zero_slots integer,
  recovered_slots integer,
  missing_slots integer,
  failed_slots integer,
  failure_classes text[],
  latest_due_slot timestamptz,
  status text,
  is_healthy boolean
)
LANGUAGE sql
STABLE
SET search_path = pg_catalog, public
AS $$
  WITH target_dates AS (
    SELECT generate_series(
      (p_observed_at AT TIME ZONE 'Asia/Ho_Chi_Minh')::date - (p_lookback_days - 1),
      (p_observed_at AT TIME ZONE 'Asia/Ho_Chi_Minh')::date,
      interval '1 day'
    )::date AS target_date
    UNION
    SELECT DISTINCT slot.slot_date_hcm
    FROM public.photo_objet_expected_slots slot
    WHERE slot.status IN ('missing', 'failed')
  ),
  slot_times(slot_time) AS (
    VALUES
      (TIME '10:00'), (TIME '12:00'), (TIME '14:00'), (TIME '16:00'),
      (TIME '18:00'), (TIME '20:00'), (TIME '23:00')
  ),
  policy_candidates AS (
    SELECT
      p.id AS policy_id,
      p.store_id,
      d.target_date,
      st.slot_time,
      r.is_active AS policy_store_active
    FROM public.photo_objet_monitoring_policies p
    JOIN public.restaurants r ON r.id = p.store_id
    CROSS JOIN target_dates d
    CROSS JOIN slot_times st
    WHERE (
        p.is_enabled = true
        OR EXISTS (
          SELECT 1
          FROM public.photo_objet_expected_slots unresolved
          WHERE unresolved.monitoring_policy_id = p.id
            AND unresolved.slot_date_hcm = d.target_date
            AND unresolved.status IN ('missing', 'failed')
        )
      )
      AND (d.target_date + st.slot_time) AT TIME ZONE p.timezone >= p.effective_from
      AND (
        p.effective_to IS NULL
        OR (d.target_date + st.slot_time) AT TIME ZONE p.timezone < p.effective_to
      )
  )
  SELECT
    c.store_id,
    c.target_date,
    count(*)::integer,
    count(s.id)::integer,
    (count(*) - count(s.id))::integer,
    bool_and(c.policy_store_active),
    count(s.id) FILTER (WHERE s.due_at <= p_observed_at)::integer,
    count(s.id) FILTER (
      WHERE s.due_at <= p_observed_at AND s.status = 'collected'
    )::integer,
    count(s.id) FILTER (
      WHERE s.due_at <= p_observed_at AND s.status = 'collected_zero'
    )::integer,
    count(s.id) FILTER (
      WHERE s.due_at <= p_observed_at AND s.status = 'recovered'
    )::integer,
    count(s.id) FILTER (
      WHERE s.due_at <= p_observed_at
        AND s.status IN ('expected', 'running', 'missing')
    )::integer,
    count(s.id) FILTER (
      WHERE s.due_at <= p_observed_at AND s.status = 'failed'
    )::integer,
    CASE
      WHEN count(s.id) <> count(*) OR bool_and(c.policy_store_active) IS DISTINCT FROM true
        THEN array_prepend(
          'AUDIT_INFRA_FAILED'::text,
          coalesce(array_agg(DISTINCT s.last_failure_class ORDER BY s.last_failure_class)
            FILTER (
              WHERE s.due_at <= p_observed_at
                AND s.status IN ('missing', 'failed')
                AND s.last_failure_class IS NOT NULL
            ), ARRAY[]::text[])
        )
      ELSE coalesce(array_agg(DISTINCT s.last_failure_class ORDER BY s.last_failure_class)
        FILTER (
          WHERE s.due_at <= p_observed_at
            AND s.status IN ('missing', 'failed')
            AND s.last_failure_class IS NOT NULL
        ), ARRAY[]::text[])
    END,
    max(s.scheduled_at) FILTER (WHERE s.due_at <= p_observed_at),
    CASE
      WHEN bool_and(c.policy_store_active) IS DISTINCT FROM true THEN 'audit_infra_failed'
      WHEN count(s.id) <> count(*) THEN 'audit_infra_failed'
      WHEN count(s.id) FILTER (WHERE s.due_at <= p_observed_at) = 0 THEN 'not_due'
      WHEN count(s.id) FILTER (
        WHERE s.due_at <= p_observed_at AND s.status = 'failed'
      ) > 0 THEN 'failed'
      WHEN count(s.id) FILTER (
        WHERE s.due_at <= p_observed_at
          AND s.status IN ('expected', 'running', 'missing')
      ) > 0 THEN 'missing'
      ELSE 'healthy'
    END,
    bool_and(c.policy_store_active)
      AND count(s.id) = count(*)
      AND count(s.id) FILTER (WHERE s.due_at <= p_observed_at) > 0
      AND count(s.id) FILTER (
        WHERE s.due_at <= p_observed_at
          AND s.status IN ('expected', 'running', 'missing', 'failed')
      ) = 0
  FROM policy_candidates c
  LEFT JOIN public.photo_objet_expected_slots s
    ON s.monitoring_policy_id = c.policy_id
   AND s.store_id = c.store_id
   AND s.slot_date_hcm = c.target_date
   AND s.slot_time_hcm = c.slot_time
  GROUP BY c.policy_id, c.store_id, c.target_date
$$;

CREATE OR REPLACE VIEW public.v_photo_objet_expected_slot_health
WITH (security_invoker = true)
AS SELECT * FROM public.photo_objet_expected_slot_health_at(now(), 2);

CREATE OR REPLACE FUNCTION public.photo_objet_collection_health_at(
  p_observed_at timestamptz DEFAULT now()
)
RETURNS TABLE (
  store_id uuid,
  target_date date,
  expected_slots integer,
  due_slots integer,
  successful_slots integer,
  failed_slots integer,
  missing_slots integer,
  missing_slot_times text[],
  failed_slot_times text[],
  latest_successful_slot timestamptz,
  next_expected_slot timestamptz,
  last_finished_at timestamptz,
  observed_at timestamptz,
  status text,
  is_healthy boolean
)
LANGUAGE sql
STABLE
SET search_path = pg_catalog, public
AS $$
  SELECT
    s.store_id,
    s.slot_date_hcm,
    count(*)::integer,
    count(*) FILTER (WHERE s.due_at <= p_observed_at)::integer,
    count(*) FILTER (
      WHERE s.due_at <= p_observed_at
        AND s.status IN ('collected', 'collected_zero', 'recovered')
    )::integer,
    count(*) FILTER (
      WHERE s.due_at <= p_observed_at AND s.status = 'failed'
    )::integer,
    count(*) FILTER (
      WHERE s.due_at <= p_observed_at
        AND s.status IN ('expected', 'running', 'missing')
    )::integer,
    coalesce(array_agg(to_char(s.slot_time_hcm, 'HH24:MI') ORDER BY s.slot_time_hcm)
      FILTER (
        WHERE s.due_at <= p_observed_at
          AND s.status IN ('expected', 'running', 'missing')
      ), ARRAY[]::text[]),
    coalesce(array_agg(to_char(s.slot_time_hcm, 'HH24:MI') ORDER BY s.slot_time_hcm)
      FILTER (WHERE s.due_at <= p_observed_at AND s.status = 'failed'),
      ARRAY[]::text[]),
    max(s.scheduled_at) FILTER (
      WHERE s.status IN ('collected', 'collected_zero', 'recovered')
    ),
    min(s.scheduled_at) FILTER (WHERE s.due_at > p_observed_at),
    max(r.finished_at) FILTER (WHERE r.status = 'success'),
    p_observed_at,
    CASE
      WHEN count(*) FILTER (WHERE s.due_at <= p_observed_at) = 0 THEN 'not_due'
      WHEN count(*) FILTER (WHERE s.due_at <= p_observed_at AND s.status = 'failed') > 0 THEN 'failed'
      WHEN count(*) FILTER (
        WHERE s.due_at <= p_observed_at
          AND s.status IN ('expected', 'running', 'missing')
      ) > 0 THEN 'missing'
      ELSE 'healthy'
    END,
    count(*) FILTER (WHERE s.due_at <= p_observed_at) > 0
      AND count(*) FILTER (
        WHERE s.due_at <= p_observed_at
          AND s.status IN ('expected', 'running', 'missing', 'failed')
      ) = 0
  FROM public.photo_objet_expected_slots s
  LEFT JOIN public.photo_objet_sales_pull_runs r ON r.id = s.successful_run_id
  GROUP BY s.store_id, s.slot_date_hcm
$$;

DO $health_view$
BEGIN
  IF to_regclass('public.v_photo_objet_collection_health') IS NULL THEN
    EXECUTE $view$
      CREATE VIEW public.v_photo_objet_collection_health
      WITH (security_invoker = true)
      AS SELECT * FROM public.photo_objet_collection_health_at(now())
    $view$;
  END IF;
END;
$health_view$;

COMMENT ON VIEW public.v_photo_objet_collection_health IS
  'Compatibility health surface backed by effective-dated expected slots and typed run identity.';

CREATE OR REPLACE VIEW public.v_office_photo_objet_expected_slot_health
WITH (security_invoker = true)
AS
SELECT health.*
FROM public.v_photo_objet_expected_slot_health health
JOIN public.v_office_eligible_stores eligible ON eligible.store_id = health.store_id;

REVOKE ALL ON FUNCTION public.photo_objet_ensure_expected_slots(date, date) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.photo_objet_claim_expected_slot(uuid, date, time, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.photo_objet_complete_expected_slot(uuid, date, time, uuid, boolean) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.photo_objet_fail_expected_slot(uuid, date, time, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.photo_objet_refresh_expected_slot_health(timestamptz, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.photo_objet_ack_expected_slot_alert(uuid, date, time, text, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.photo_objet_claim_expected_slot(uuid, date, time, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.photo_objet_complete_expected_slot(uuid, date, time, uuid, boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.photo_objet_fail_expected_slot(uuid, date, time, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.photo_objet_refresh_expected_slot_health(timestamptz, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.photo_objet_ack_expected_slot_alert(uuid, date, time, text, timestamptz) TO service_role;

REVOKE ALL ON FUNCTION public.photo_objet_expected_slot_health_at(timestamptz, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.photo_objet_expected_slot_health_at(timestamptz, integer)
  TO authenticated, service_role;
REVOKE ALL ON public.v_photo_objet_expected_slot_health FROM PUBLIC, anon;
GRANT SELECT ON public.v_photo_objet_expected_slot_health TO authenticated, service_role;
REVOKE ALL ON public.v_office_photo_objet_expected_slot_health FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.v_office_photo_objet_expected_slot_health TO service_role;

COMMENT ON TABLE public.photo_objet_monitoring_policies IS
  'Effective-dated source of truth for independently generated Photo Objet scheduler expectations.';
COMMENT ON TABLE public.photo_objet_expected_slots IS
  'One immutable scheduler identity per store/date/time; raw Moers sales remain in their separate append-only ledger.';
COMMENT ON FUNCTION public.photo_objet_expected_slot_health_at(timestamptz, integer) IS
  'Read-only exact-slot health used by release proof. It never parses error_message metadata.';

-- The database materializes expectations independently of GitHub Actions and
-- the Moers collector. Supabase production already provides pg_cron; local
-- replay environments without it still validate the function directly.
DO $schedule$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'photo-objet-materialize-expected-slots') THEN
      PERFORM cron.unschedule('photo-objet-materialize-expected-slots');
    END IF;
    PERFORM cron.schedule(
      'photo-objet-materialize-expected-slots',
      '5 17 * * *',
      $command$SELECT public.photo_objet_ensure_expected_slots(
        (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::date,
        (now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::date
      )$command$
    );
  END IF;
END;
$schedule$;
